In [24]:
import numpy as np
import random
import pandas as pd

In [10]:
x=np.arange(12).reshape(3,4)
y = np.ones([1,4])
x = np.concatenate([y,x],axis=0)
print(x)

[[ 1.  1.  1.  1.]
 [ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [17]:
x=np.random.permutation(10)
print(x)

[9 1 2 3 4 6 5 7 8 0]


In [21]:
x = np.arange(12)-1
print(x)
print(np.count_nonzero(x))

[-1  0  1  2  3  4  5  6  7  8  9 10]
11


In [25]:
df = pd.read_excel("data.xlsx", sheet_name="data")
data = df.to_numpy()
print(data)
xdata = data[:,2:]
n,d = xdata.shape
ydata = data[:,1].reshape(n)
print(ydata)
ydata[ydata == 'M'] = -1
ydata[ydata == 'B'] = 1
print(ydata)

[[842302 'M' 17.99 ... 0.2654 0.4601 0.1189]
 [842517 'M' 20.57 ... 0.186 0.275 0.08902]
 [84300903 'M' 19.69 ... 0.243 0.3613 0.08758]
 ...
 [926954 'M' 16.6 ... 0.1418 0.2218 0.0782]
 [927241 'M' 20.6 ... 0.265 0.4087 0.124]
 [92751 'B' 7.76 ... 0.0 0.2871 0.07039]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 

In [33]:
print(np.nonzero(ydata+1))

(array([ 19,  20,  21,  37,  46,  48,  49,  50,  51,  52,  55,  58,  59,
        60,  61,  63,  66,  67,  68,  69,  71,  74,  76,  79,  80,  81,
        84,  88,  89,  90,  92,  93,  96,  97,  98, 101, 102, 103, 104,
       106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 120, 123, 124,
       125, 128, 130, 133, 136, 137, 139, 140, 142, 143, 144, 145, 147,
       148, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 160, 163,
       165, 166, 169, 170, 173, 174, 175, 176, 178, 179, 183, 185, 187,
       188, 189, 191, 192, 195, 200, 204, 206, 208, 209, 211, 216, 217,
       220, 221, 222, 224, 225, 226, 227, 228, 231, 232, 234, 235, 238,
       240, 241, 242, 243, 245, 246, 247, 248, 249, 251, 266, 267, 268,
       269, 270, 271, 273, 275, 276, 278, 279, 281, 284, 285, 286, 287,
       288, 289, 290, 291, 292, 293, 294, 295, 296, 298, 299, 301, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       318, 319, 320, 322, 324, 325, 326, 327, 331, 332, 333, 3