In [1]:
import numpy as np
import random
import pandas as pd

In [2]:
x=np.arange(12).reshape(3,4)
y = np.ones([1,4])
x = np.concatenate([y,x],axis=0)
print(x)

[[ 1.  1.  1.  1.]
 [ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [3]:
x=np.random.permutation(10)
print(x)

[2 7 0 6 1 4 5 3 8 9]


In [21]:
x = np.arange(12)-1
print(x)
print(np.count_nonzero(x))

[-1  0  1  2  3  4  5  6  7  8  9 10]
11


In [4]:
df = pd.read_excel("data.xlsx", sheet_name="data")
data = df.to_numpy()
print(data)
xdata = data[:,2:]
n,d = xdata.shape
ydata = data[:,1].reshape(n)
print(ydata)
ydata[ydata == 'M'] = -1
ydata[ydata == 'B'] = 1
print(ydata)

[[842302 'M' 17.99 ... 0.2654 0.4601 0.1189]
 [842517 'M' 20.57 ... 0.186 0.275 0.08902]
 [84300903 'M' 19.69 ... 0.243 0.3613 0.08758]
 ...
 [926954 'M' 16.6 ... 0.1418 0.2218 0.0782]
 [927241 'M' 20.6 ... 0.265 0.4087 0.124]
 [92751 'B' 7.76 ... 0.0 0.2871 0.07039]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 

In [33]:
print(np.nonzero(ydata+1))

(array([ 19,  20,  21,  37,  46,  48,  49,  50,  51,  52,  55,  58,  59,
        60,  61,  63,  66,  67,  68,  69,  71,  74,  76,  79,  80,  81,
        84,  88,  89,  90,  92,  93,  96,  97,  98, 101, 102, 103, 104,
       106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 120, 123, 124,
       125, 128, 130, 133, 136, 137, 139, 140, 142, 143, 144, 145, 147,
       148, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 160, 163,
       165, 166, 169, 170, 173, 174, 175, 176, 178, 179, 183, 185, 187,
       188, 189, 191, 192, 195, 200, 204, 206, 208, 209, 211, 216, 217,
       220, 221, 222, 224, 225, 226, 227, 228, 231, 232, 234, 235, 238,
       240, 241, 242, 243, 245, 246, 247, 248, 249, 251, 266, 267, 268,
       269, 270, 271, 273, 275, 276, 278, 279, 281, 284, 285, 286, 287,
       288, 289, 290, 291, 292, 293, 294, 295, 296, 298, 299, 301, 303,
       304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316,
       318, 319, 320, 322, 324, 325, 326, 327, 331, 332, 333, 3

In [18]:
print(np.mean(xdata,axis=0))
xdata = np.float32(xdata)
(xdata-np.mean(xdata,axis=0).reshape([1,d]))/np.std(xdata,axis=0)

[1.4125e+01 1.9297e+01 9.2000e+01 6.5500e+02 9.6375e-02 1.0437e-01
 8.8806e-02 4.8920e-02 1.8115e-01 6.2805e-02 4.0527e-01 1.2168e+00
 2.8652e+00 4.0344e+01 7.0419e-03 2.5482e-02 3.1891e-02 1.1795e-02
 2.0538e-02 3.7956e-03 1.6266e+01 2.5672e+01 1.0725e+02 8.8050e+02
 1.3232e-01 2.5415e-01 2.7222e-01 1.1462e-01 2.9004e-01 8.3923e-02]


array([[ 1.0954976 , -2.0725486 ,  1.2704041 , ...,  2.2957652 ,
         2.752418  ,  1.9366789 ],
       [ 1.827735  , -0.35462084,  1.6848747 , ...,  1.0876011 ,
        -0.24539405,  0.28283045],
       [ 1.579218  ,  0.45616832,  1.5664545 , ...,  1.9556205 ,
         1.152795  ,  0.20165996],
       ...,
       [ 0.7005332 ,  2.0450242 ,  0.67315453, ...,  0.41474658,
        -1.1044508 , -0.31918392],
       [ 1.8366106 ,  2.3358903 ,  1.9834994 , ...,  2.2883303 ,
         1.9190342 ,  2.2207756 ],
       [-1.8079344 ,  1.2233275 , -1.8149561 , ..., -1.7450793 ,
        -0.04790972, -0.75209314]], dtype=float32)